export const kangaroos = [
  {
    id: "1",
    name: "kangaroo-1",
    nickname: "kangaroooo",
    weight: "123",
    height: "123",
    gender: "Male",
    color: "black",
    friendliness: "Friendly",
    birthday: new Date(),
  },
  {
    id: "2",
    name: "kangaroo-2",
    nickname: "kangaroooo",
    weight: "2222",
    height: "1222223",
    gender: "Male",
    color: "black",
    friendliness: "Friendly",
    birthday: new Date(),
  },
  {
    id: "3",
    name: "kangaroo-3",
    nickname: "kangaroooo",
    weight: "10",
    height: "25",
    gender: "Female",
    color: "blue",
    friendliness: "Not Friendly",
    birthday: new Date(),
  },
];
